### ISSUE TITLE
[Feature request] Slider with custom Vector (instead of range)

### ISSUE THREAD

**Issue by briochemc** [JuliaPluto/PlutoUI.jl#25]
How can one create a slider that is indexed onto an array but that binds to the *values* of the array? 

E.g., say I have an array of values with a custom type, e.g.,
```julia
using Unitful: m
my_array = [0.0, 1.0, 3.0, 5.0, 10.0, 30.0, 50.0]m
```
I would like a slider to pick one of these values.

Ideally, it'd be great to be able to create that slider with just
```julia
Slider(my_array)
```

**Comment by lungben** [comment]
The html range input element only support ranges, not custom vectors.
But it should be possible to have the custom vector just on Julia side and use the html range as index.
If I have some time tomorrow, I'll take a look at it.

**Comment by not-fred** [comment]
It looks like we'll need some modifications to the Pluto.jl core, because the default behaviour of `@bind ` is to directly assign the value given by the frontend, which is sent via WebSocket, so we're limited to real numbers and strings.

I've had _some_ success by encoding the value in the frontend as a string, then having the backend convert the string back into the correct type. It kind of works
![matrix](https://user-images.githubusercontent.com/7859260/92330996-c2ff4200-f0a5-11ea-8f03-f108440fef12.gif)
_but_ only if it can be defined similar to the way it is printed (e.g. matrices `[1 2; 3 4]::Array{Int64,2}` and chars `'A'::Char`).

A better way would be to store the vector in a hidden variable as suggested by @lungben, but we'll need to write different handlers for the text inputs and checkboxes/sliders/radios on the receiving end of `@bind` in the Pluto.jl side.

**Comment by fonsp** [comment]
Also have a look here: https://github.com/fonsp/PlutoUI.jl/issues/3#issuecomment-626708301

**Comment by lungben** [comment]
It looks like the bind macro uses the `get` function to fetch the current value:
`global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : missing`
Maybe it is possible to define a new struct `CustomSlider <: Abstract Slider` with its own get method to handle the output?
I'll check tomorrow.

**Comment by fonsp** [comment]
It does **not** use `get` to fetch the current value - `get` defines the initial value, before JS is involved.

But my proposed solution is to optionally use a 2-argument `Base.get` overload to transform values:

https://github.com/fonsp/PlutoUI.jl/issues/3#issuecomment-629724036

**Comment by lungben** [comment]
Sorry read your last comment only after having posted mine, seems that I have not fully understood the code :-(
Your suggestion sounds good!
