### ISSUE TITLE
Instability in return type of PlutoUI.Slider

### ISSUE THREAD

**Issue by NitishGadangi** [JuliaPluto/PlutoUI.jl#64]
**issue description:**
The return type of PlutoUI.Slider is Int64 in few instances and Float64 in few instances

![image-1603965448996](https://user-images.githubusercontent.com/29014716/97553320-4cbef200-19fb-11eb-9564-c2304ff73896.png)

**expected behavior:**
the return type must be stable

**remarks**
right now, the possible workaround is using Float64(var) or Int64(var) where ever required. But, it is not ideal to explicitly type Float64 everywhere.

**Comment by fonsp** [comment]
(This has the the same solution as #25 and #21 )

**Comment by juliohm** [comment]
Can you elaborate on the solution @fonsp ? It isn't clear from the comments in the other issues. What is happening that is making the slider type unstable? I looked into the source and couldn't spot a reason.

**Comment by fonsp** [comment]
To be clear, there is no solution yet, but it _would_ be solved by #25. 

The problem is that JavaScript is sending the slider values, but JS only has one Number type (Float64 I think). Based on whether the slider value is rounded or not, it sends an integer or float, causing this problem.

#25 would circumvent these issues because
